name: Deploy-application

on: 
  push:
    branches:
      - main

jobs:
  check_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '*/packages-lock.json'

      - name: Install dependencies
        run: npm ci
      
      - name: Run lint fix
        run: npm run lint
  
  run_tests:
    runs-on: ubuntu-latest
    needs: [check_lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '*/packages-lock.json'

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm run test

  deploy_to_vercel:
    runs-on: ubuntu-latest
    needs: [check_lint, run_tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: deploy site to vercel      
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}